"""Initial schema

Revision ID: 2db26230ada0
Revises: 
Create Date: 2025-07-22 16:19:13.255694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db26230ada0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('ID', sa.BigInteger(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Surname', sa.String(length=255), nullable=False),
    sa.Column('DateOfBirth', sa.DateTime(), nullable=False),
    sa.Column('PlaceOfBirth', sa.String(length=255), nullable=False),
    sa.Column('Gender', sa.String(length=20), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=30), nullable=False),
    sa.Column('EmailAddress', sa.String(length=255), nullable=False),
    sa.Column('ProvinceOfResidence', sa.String(length=255), nullable=False),
    sa.Column('CountryOfAsylum', sa.String(length=255), nullable=False),
    sa.Column('Nationality', sa.String(length=255), nullable=False),
    sa.Column('NationalIdNumber', sa.String(length=255), nullable=True),
    sa.Column('CountryOfAsylumRegistrationNumber', sa.String(length=255), nullable=True),
    sa.Column('UnhcrIndividualId', sa.String(length=255), nullable=True),
    sa.Column('HouseholdPersonCount', sa.Integer(), nullable=True),
    sa.Column('ReceiveMessagesFromUnhcr', sa.Boolean(), nullable=True),
    sa.Column('ReceiveNotificationsFromUnhcr', sa.Boolean(), nullable=True),
    sa.Column('ReceiveSurveysFromUnhcr', sa.Boolean(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_User_EmailAddress'), 'User', ['EmailAddress'], unique=True)
    op.create_index(op.f('ix_User_ID'), 'User', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_ID'), table_name='User')
    op.drop_index(op.f('ix_User_EmailAddress'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
