from csv import reader
import os

caseTypeChoices = [
    ("Health", "Health"),
    ("Education", "Education"),
    ("Food Assistance", "Food Assistance"),
    ("Cash Assistance", "Cash Assistance"),
    ("Legal Support", "Legal Support"),
    ("NFI Support", "NFI Support"),
    ("Protection From Violence", "Protection From Violence"),
    ("MHPSS", "MHPSS"),
    ("Child Protection", "Child Protection"),
    ("Detention/Deportation", "Detention/Deportation"),
    ("Other", "Other")
]

psnTypeChoices = [
    ("Pregnant", "Pregnant"),
    ("Elderly", "Elderly"),
    ("Unaccompanied And/Or Seperated Children", "Unaccompanied And/Or Seperated Children"),
    ("Chronic Disease", "Chronic Disease"),
    ("Disability", "Disability"),
]

caseStatusChoices = [
    ("REQUEST RECEIVED", "Request Received"),
    ("REQUEST VIEWED", "Request Viewed"),
    ("REQUEST REFERRED", "Request Referred"),
    ("CASE WORKER ASSIGNED", "Case Worker Assigned"),
    ("FIRST CONTACT SCHEDULED", "First Contact Scheduled"),
    ("CASE CLOSED", "Case Closed")
]

caseCoverageChoices = [
    ("INDIVIDUAL", "Individual"),
    ("HOUSEHOLD", "Household")
]

userGenderChoices = [
    "Male",
    "Female",
    "Non Binary",
    "Other"
]

vulnerabilityCategoryChoices = [
    ("LOW RISK", "Low Risk"),
    ("MODERATE RISK", "Moderate Risk"),
    ("HIGH RISK", "High Risk"),
]

caseFeedbackRatingChoices = [
    (1, 'One'),
    (2, 'Two'),
    (3, 'Three'),
    (4, 'Four'),
    (5, 'Five'),
]

userCountryOfAsylumChoices = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "The Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Republic of the Congo",
    "Democratic Republic of the Congo",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Denmark",
    "Djibuti",
    "Dominica Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "The Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "North Korea",
    "South Korea",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Federated States of Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nepal",
    "The Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugual",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "São Tomé and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
]

userNationalityChoices = userCountryOfAsylumChoices

# For generating countries choices from the CSV file
""" print(os.getcwd())
with open('./EndUserManagement/models/countries.csv', 'r') as read_obj:
    # pass the file object to reader() to get the reader object
    csv_reader = reader(read_obj)
    # Iterate over each row in the csv using reader object
    for row in csv_reader:
        # row variable is a list that represents a row in csv
        # print(row)
        print(f'("{row[1]}", "{row[3]}"),') """
